name: dailyReset
on:   
    schedule:
      - cron: "0 6 * * *"
    workflow_dispatch:

jobs:
  test:
    name: reset
    runs-on : ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js and cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: set dotenv
        run: |
          echo "VITE_SUPABASE_ANON_KEY=${{secrets.VITE_SUPABASE_ANON_KEY}}" >> .env
          echo "VITE_SUPABASE_URL=${{secrets.VITE_SUPABASE_URL}}" >> .env
      - name: Install dependencies
        run: npm ci
      - name: Run jobs
        run: npx tsx --tsconfig ./tsconfig.app.json ./batch/index.ts 
      - name: delete dotenv
        run: rm .env
